name: express
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^1.0.5
    #  permission_handler: ^11.1.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  provider: ^6.1.1
  animation_wrappers: ^3.0.0
  loading_animation_widget: ^1.2.0+4
  esc_pos_printer_plus: ^0.0.3
  esc_pos_utils_plus: ^2.0.3
  ping_discover_network_plus: ^0.0.5
  image: ^4.1.3
  charset_converter: ^2.1.1
  path_provider: ^2.1.1
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_advanced_drawer: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/baghasht.jpeg"
  image_path_android: "assets/baghasht.jpeg"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/baghasht.jpeg"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter:

  uses-material-design: true

  assets:
    - assets/
