// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK8InJrBFjuAQ5fO2HB6kB4QH74ge9YCk',
    appId: '1:352485659330:web:5de1d642f1d203def8a15b',
    messagingSenderId: '352485659330',
    projectId: 'edsgym-27350',
    authDomain: 'edsgym-27350.firebaseapp.com',
    storageBucket: 'edsgym-27350.appspot.com',
    measurementId: 'G-YPJ3YVF8KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR6XbIQTXAIJRlmABlZv7AY6AZIhdQZfI',
    appId: '1:352485659330:android:466c8630ee8029e2f8a15b',
    messagingSenderId: '352485659330',
    projectId: 'edsgym-27350',
    storageBucket: 'edsgym-27350.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPAr8mZXZ6lOaURtE9PfWmNQed8R5FIgo',
    appId: '1:352485659330:ios:7faf24681c6c7004f8a15b',
    messagingSenderId: '352485659330',
    projectId: 'edsgym-27350',
    storageBucket: 'edsgym-27350.appspot.com',
    iosClientId: '352485659330-cj63a4pjn3bnjp4rmgoebml345uj2iv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.express',
  );
}
